# Generated by Django 5.0 on 2023-12-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.TextField()),
                ('cardimagefront', models.TextField()),
                ('carfimageback', models.TextField()),
            ],
        ),
    ]
