# Generated by Django 5.0 on 2023-12-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='cardimagefront',
            new_name='imageurl',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='carfimageback',
            new_name='imageurl1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='profileimage',
            new_name='imageurl2',
        ),
    ]
