# Generated by Django 5.0 on 2023-12-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_rename_cardimagefront_register_imageurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='state',
            new_name='stateorigin',
        ),
    ]
