# Generated by Django 5.0 on 2023-12-16 19:44

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_rename_state_register_stateorigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='accountbal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='register',
            name='accountnumber',
            field=models.TextField(default=backend_app.models.getRandom),
        ),
        migrations.AddField(
            model_name='register',
            name='accountype',
            field=models.TextField(default='Not Available'),
        ),
    ]
