# Generated by Django 5.0 on 2024-02-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_register_accountbal_register_accountnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('account', models.CharField(max_length=255)),
                ('accounttype', models.CharField(max_length=255)),
                ('accountbal', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('accountNo', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
    ]
