# Generated by Django 5.0 on 2024-02-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_localtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='localtransfer',
            name='to_fname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='to_lname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='localtransfer',
            name='trans_date',
            field=models.DateField(auto_now=True),
        ),
    ]
