# Generated by Django 4.1.5 on 2024-09-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_saveaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalTransfer',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='SaveAccount',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='accountnumber',
            new_name='accessnumber',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='city',
            new_name='mname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='accountbal',
        ),
        migrations.RemoveField(
            model_name='register',
            name='accountype',
        ),
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='register',
            name='confirmsocialsecurity',
        ),
        migrations.RemoveField(
            model_name='register',
            name='country',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='register',
            name='imageurl1',
        ),
        migrations.RemoveField(
            model_name='register',
            name='imageurl2',
        ),
        migrations.RemoveField(
            model_name='register',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='socialsecurity',
        ),
        migrations.RemoveField(
            model_name='register',
            name='stateorigin',
        ),
        migrations.RemoveField(
            model_name='register',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.RemoveField(
            model_name='register',
            name='zipcode',
        ),
    ]
