# Generated by Django 4.1.5 on 2024-09-30 15:09

import backend_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_delete_localtransfer_delete_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=backend_app.models.file_upload_to)),
                ('file_date', models.DateField(auto_now_add=True)),
                ('fileowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.register', to_field='email')),
            ],
        ),
    ]
