# Generated by Django 4.1.5 on 2024-10-01 07:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_alter_register_email_uploadedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='uploaded_file',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images'),
        ),
    ]
