# Generated by Django 4.1.5 on 2024-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_uploadedfiles_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='uploaded_file',
            field=models.TextField(),
        ),
    ]
