# Generated by Django 4.1.5 on 2024-10-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_alter_uploadedfiles_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='fileowner',
            field=models.CharField(max_length=255),
        ),
    ]
