# Generated by Django 4.1.5 on 2024-10-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_alter_uploadedfiles_fileowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
