# Generated by Django 4.1.5 on 2024-10-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_alter_register_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFiles',
        ),
    ]
