# Generated by Django 4.1.5 on 2024-10-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_delete_uploadedfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileowner', models.CharField(max_length=255)),
                ('uploaded_file', models.TextField()),
                ('file_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
