# Generated by Django 4.1.5 on 2024-10-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_uploadedfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='filereceiver',
            field=models.CharField(default='', max_length=255),
        ),
    ]
