# Generated by Django 4.1.5 on 2024-10-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0018_uploadedfiles_filereceiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='filereceiver',
            new_name='filesender',
        ),
    ]
