# Generated by Django 4.1.5 on 2024-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0019_rename_filereceiver_uploadedfiles_filesender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileowner', models.CharField(max_length=255)),
                ('filesender', models.CharField(max_length=255)),
                ('uploaded_audio', models.TextField()),
                ('file_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
