# Generated by Django 4.1.5 on 2024-10-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0021_uploadedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteowner', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('nodedate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
