# Generated by Django 4.1.5 on 2024-10-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
