# Generated by Django 4.1.5 on 2024-10-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_student_delete_form1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
