# Generated by Django 4.1.5 on 2024-10-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_formtemplate_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='form_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
