# Generated by Django 4.1.5 on 2024-10-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0030_uploadedpdffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdffile',
            old_name='uploaded_text',
            new_name='uploaded_pdf',
        ),
    ]
