# Generated by Django 4.1.5 on 2024-10-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0032_register1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register1',
        ),
    ]
