# Generated by Django 5.1.3 on 2024-11-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0033_delete_register1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='accessnumber',
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
