# Generated by Django 5.1.3 on 2024-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0034_remove_register_accessnumber_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberEmail', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('accessnumber', models.CharField(max_length=255)),
                ('member_owner', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=255)),
            ],
        ),
    ]
