# Generated by Django 5.1.3 on 2024-11-17 19:35

import backend_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0035_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='accessnumber',
            field=models.CharField(default=backend_app.models.getRandom),
        ),
    ]
