# Generated by Django 5.1.3 on 2024-11-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0036_alter_member_accessnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='verifyemail',
            field=models.IntegerField(default=0),
        ),
    ]
