# Generated by Django 5.1.3 on 2024-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0040_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='community_owner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
