# Generated by Django 5.1.3 on 2024-12-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0041_member_community_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseWebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
