# Generated by Django 5.1.3 on 2024-12-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0042_coursewebuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursewebuser',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursewebuser',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursewebuser',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursewebuser',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coursewebuser',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
