# Generated by Django 5.1.3 on 2024-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0043_coursewebuser_password_alter_coursewebuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursewebuser',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
