# Generated by Django 5.1.3 on 2024-12-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0045_alarm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='status',
            new_name='email',
        ),
    ]
