# Generated by Django 5.1.3 on 2025-02-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0046_rename_status_alarm_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursewebuser',
            name='address',
        ),
    ]
