# Generated by Django 5.1.3 on 2025-02-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0047_remove_coursewebuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('video', models.TextField(default='')),
                ('amount', models.FloatField(default=0)),
                ('coursedetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.coursedetails', to_field='description')),
            ],
        ),
    ]
