# Generated by Django 5.1.3 on 2025-02-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0047_remove_coursewebuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', unique=True)),
                ('image', models.TextField(default='')),
                ('video', models.TextField(default='')),
                ('amount', models.FloatField(default=0)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_app.owner', to_field='ownername')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('course_content', models.TextField(default='')),
                ('sub_content', models.TextField(default='')),
                ('content_video', models.TextField(default='')),
                ('tutorial', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_app.tutorial', to_field='title')),
            ],
        ),
    ]
