# Generated by Django 5.1.3 on 2025-02-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0048_owner_tutorial_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.CharField(default='', max_length=255)),
                ('item', models.TextField(default='')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
