# Generated by Django 5.1.3 on 2025-02-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0048_coursedetails_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorname', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_app.tutor', to_field='tutorname'),
        ),
    ]
