# Generated by Django 5.1.3 on 2025-02-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0049_tutor_course_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('course_title', models.TextField(default='', unique=True)),
                ('subtitle', models.TextField(default='')),
                ('video', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='coursecontent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend_app.coursecontent', to_field='course_title'),
        ),
    ]
