# Generated by Django 5.1.3 on 2025-02-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0050_cartitems_tutorial_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createfolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_folder', models.TextField(default='')),
            ],
        ),
    ]
