# Generated by Django 5.1.3 on 2025-02-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0051_createfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Createfolder',
        ),
    ]
