# Generated by Django 5.1.3 on 2025-02-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0052_delete_createfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newfolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_link', models.TextField(default='')),
            ],
        ),
    ]
