# Generated by Django 5.1.3 on 2025-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0053_newfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfolder',
            name='f_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='newfolder',
            name='f_owner',
            field=models.CharField(default='', max_length=255),
        ),
    ]
