# Generated by Django 5.1.3 on 2025-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0054_newfolder_f_name_newfolder_f_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_id', models.IntegerField(default=0)),
                ('emailId', models.CharField(default='')),
                ('tutorial_name', models.TextField(default='')),
            ],
        ),
    ]
