# Generated by Django 5.1.3 on 2025-02-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0055_mylearning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylearning',
            name='tutorial_name',
        ),
    ]
