# Generated by Django 5.1.3 on 2025-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0056_remove_mylearning_tutorial_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileToFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.IntegerField(default=0)),
                ('folder_name', models.CharField(default='', max_length=255)),
                ('folder_owner', models.CharField(default='', max_length=255)),
                ('uploaded_link', models.TextField(default='')),
            ],
        ),
    ]
