# Generated by Django 5.1.3 on 2025-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0057_uploadfiletofolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiletofolder',
            name='fileName',
            field=models.CharField(default=''),
        ),
    ]
