# Generated by Django 5.1.3 on 2025-03-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0058_uploadfiletofolder_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiletofolder',
            name='fileSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfiletofolder',
            name='fileType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadfiletofolder',
            name='lastModifiedDate',
            field=models.TextField(default=''),
        ),
    ]
