# Generated by Django 5.1.3 on 2025-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0060_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head1', models.CharField(default='', max_length=255)),
                ('head2', models.CharField(default='', max_length=255)),
                ('head3', models.CharField(default='', max_length=255)),
                ('head4', models.CharField(default='', max_length=255)),
                ('value11', models.CharField(default='', max_length=255)),
                ('value12', models.CharField(default='', max_length=255)),
                ('value13', models.CharField(default='', max_length=255)),
                ('value14', models.CharField(default='', max_length=255)),
                ('value21', models.CharField(default='', max_length=255)),
                ('value22', models.CharField(default='', max_length=255)),
                ('value23', models.CharField(default='', max_length=255)),
                ('value24', models.CharField(default='', max_length=255)),
                ('value31', models.CharField(default='', max_length=255)),
                ('value32', models.CharField(default='', max_length=255)),
                ('value33', models.CharField(default='', max_length=255)),
                ('value34', models.CharField(default='', max_length=255)),
                ('value41', models.CharField(default='', max_length=255)),
                ('value42', models.CharField(default='', max_length=255)),
                ('value43', models.CharField(default='', max_length=255)),
                ('value44', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
