# Generated by Django 5.1.3 on 2025-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0061_tabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='emailId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tabledata',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
