# Generated by Django 5.1.3 on 2025-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0062_tabledata_emailid_tabledata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='value21',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value22',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value23',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value24',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value31',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value32',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value33',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value34',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value41',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value42',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value43',
            field=models.CharField(default='data', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='value44',
            field=models.CharField(default='data', max_length=255),
        ),
    ]
