# Generated by Django 5.2.4 on 2025-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0065_groupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='groupname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
