# Generated by Django 5.2.4 on 2025-07-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0066_groupmembers_groupname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='groupname',
            new_name='group_name',
        ),
    ]
