# Generated by Django 5.2.4 on 2025-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0067_rename_groupname_groupmembers_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uploaded', models.CharField(max_length=255)),
                ('id_group', models.CharField(max_length=255)),
                ('name_group', models.CharField(max_length=255)),
            ],
        ),
    ]
