# Generated by Django 5.2.4 on 2025-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0068_groupupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupupload',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
