# Generated by Django 5.2.4 on 2025-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0069_groupupload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='groupId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
